openapi: 3.0.0
info:
  title: NCASA
  description: NCASA
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Scodus
    url: https://scodus.com
    email: scodusnp@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: https://ncasa.scodus.com/api
    description: Base URL
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
tags:
  - name: bus booking
  - name: bus schedule
  - name: user
  - name: payment
  - name: payment > esewa
  - name: payment > khalti
  - name: payment > connectips
  - name: payment > prabhupay
  - name: payment > fonepay
paths:
  /pre-booking:
    get:
      tags:
        - bus booking
      summary: pre booking
      security:
        - bearerAuth: []
      parameters:
        - name: schedule_id
          in: query
          schema:
            type: integer
          example: '69'
        - name: seat_id[]
          in: query
          schema:
            type: integer
          example: '6'
        - name: from
          in: query
          schema:
            type: integer
          example: '1'
        - name: to
          in: query
          schema:
            type: integer
          example: '2'
        - name: date
          in: query
          schema:
            type: string
          example: '2079-08-29'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pre-booking-timeout:
    post:
      tags:
        - bus booking
      summary: pre booking timeout
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                schedule_id:
                  type: integer
                  example: '69'
                seat_id[]:
                  type: integer
                  example: '38'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /bus-booking:
    post:
      tags:
        - bus booking
      summary: store booking
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                schedule_id: 69
                route_id: 1
                drop_location: drop location here
                rate: 2500
                qty: 1
                discount: ''
                total: 1000
                contact_name: Lal Bahadur
                contact_phone: '98713264'
                paid: ''
                due: ''
                return: ''
                bus_details: asdasd
                seat_id:
                  - '6'
                  - '7'
                payment_status: pending
                status: OnBooking
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /bus-booking/{booking_id}/cancel:
    post:
      tags:
        - bus booking
      summary: cancel booking
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                schedule_id: 51
                route_id: 1
                drop_location: drop location here
                rate: 2500
                qty: 4
                discount: ''
                total: 10000
                contact_name: Lal Bahadur
                contact_phone: '98713264'
                paid: ''
                due: ''
                return: ''
                bus_details: asdasd
                seat_id:
                  - '24'
                  - '35'
                  - '25'
                  - '36'
      security:
        - bearerAuth: []
      parameters:
        - name: booking_id
          in: path
          schema:
            type: integer
          required: true
          example: '219'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /my-booking:
    get:
      tags:
        - bus booking
      summary: my booking
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /search-bus:
    get:
      tags:
        - bus schedule
      summary: search bus
      parameters:
        - name: from
          in: query
          schema:
            type: integer
          example: '1'
        - name: to
          in: query
          schema:
            type: integer
          example: '2'
        - name: date
          in: query
          schema:
            type: string
          example: '2079-08-29'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /get-bus-seats/{bus_schedule_id}:
    get:
      tags:
        - bus schedule
      summary: get bus seat
      parameters:
        - name: bus_schedule_id
          in: path
          schema:
            type: integer
          required: true
          example: '69'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /user-detail:
    get:
      tags:
        - user
      summary: get
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - user
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: customer1
                first_name:
                  type: string
                  example: customer
                last_name:
                  type: string
                  example: test
                phone:
                  type: integer
                  example: '9876543210'
                ip_address:
                  type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/esewa/success:
    post:
      tags:
        - payment > esewa
      summary: transaction_success-verification POST
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                oid:
                  type: integer
                  example: '258'
                amt:
                  type: integer
                  example: '2500'
                refId:
                  type: string
                  example: 0004Q1T
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/esewa/fail:
    post:
      tags:
        - payment > esewa
      summary: transaction_failure POST
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                booking_id:
                  type: integer
                  example: '102'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/khalti/success:
    post:
      tags:
        - payment > khalti
      summary: transaction_success-verification POST
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: VGMyaKVDQQyorBiQ3W99WL
                amount:
                  type: integer
                  example: '2500'
                mobile:
                  type: integer
                  example: '9876543210'
                product_identity:
                  type: integer
                  example: '342'
                product_name:
                  type: string
                  example: ticket
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/khalti/fail:
    post:
      tags:
        - payment > khalti
      summary: transaction_failure POST
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '""'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/connectips/success:
    post:
      tags:
        - payment > connectips
      summary: transaction_success-verification POST
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                PRN: dsfdsf
                AMT: 2500
                mobile: 9876543210
                PID: 238
                BID: BID
                UID: UID
                RU: RU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/connectips/fail:
    post:
      tags:
        - payment > connectips
      summary: transaction_failure POST
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                booking_id:
                  type: integer
                  example: '102'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/prabhupay/success:
    post:
      tags:
        - payment > prabhupay
      summary: transaction_success-verification POST
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                transId: dsfdsf
                sellingCurrencyAmount: 2500
                accountingCurrencyAmount: 2500
                status: 200
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/prabhupay/fail:
    post:
      tags:
        - payment > prabhupay
      summary: transaction_failure POST Copy
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                booking_id:
                  type: integer
                  example: '102'
                amt:
                  type: integer
                  example: '2500'
                refId:
                  type: string
                  example: 0004Q1T
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/fonepay/success:
    post:
      tags:
        - payment > fonepay
      summary: transaction_success-verification POST
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                PRN: dsfdsf
                AMT: 2500
                mobile: 9876543210
                PID: 238
                BID: BID
                UID: UID
                RU: RU
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/fonepay/fail:
    post:
      tags:
        - payment > fonepay
      summary: transaction_failure POST
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                booking_id:
                  type: integer
                  example: '102'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /register:
    post:
      tags:
        - default
      summary: register
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: tomnjerry
                last_name:
                  type: string
                  example: jerry
                phone:
                  type: integer
                  example: '987654321'
                email:
                  type: string
                  example: tomnjerry8963@gmail.com
                password:
                  type: string
                  example: P@ssw0rd
                password_confirmation:
                  type: string
                  example: P@ssw0rd
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: customer1@customer.com
                password:
                  type: integer
                  example: '1234'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /logout:
    post:
      tags:
        - default
      summary: logout
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /refresh-token/{refresh_token}:
    post:
      tags:
        - default
      summary: refresh token
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
      security:
        - noauthAuth: []
      parameters:
        - name: refresh_token
          in: path
          schema:
            type: string
          required: true
          example: '{{refresh_token}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /resend-account-verification-mail:
    post:
      tags:
        - default
      summary: resend email verification mail
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /reset-password-mail:
    post:
      tags:
        - default
      summary: send reset password mail
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: tomnjerry8963@gmail.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /reset-password:
    post:
      tags:
        - default
      summary: reset password
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: P@ssw0rd
                password_confirmation:
                  type: string
                  example: P@ssw0rd
                token:
                  type: string
                  example: >-
                    A5C7IKsPYLX6iCrHlQUmHdbQGX8CXSHN0TiW2nygkIn7EzJlKGBjXtiF1SGyU0Xm
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /location:
    get:
      tags:
        - default
      summary: location
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
